### ISSUE TITLE
Slime Rancher 2 not loading, no error message

### ISSUE THREAD

**Issue by milosworks** [LavaGang/MelonLoader#1017]
### All of the following criteria must be met

- [x] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [x] Changed the title so that it doesn't just says "[Bug]: "
- [x] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [x] Tried reinstalling MelonLoader.
- [x] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Slime Rancher 2 does NOT open, it brings the steam loading popup but it does NOT load the game, it doesnt even "crash" it just doesnt start

[25-9-28_8-33-2.log](https://github.com/user-attachments/files/22583267/25-9-28_8-33-2.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by nicopop** [comment]
I have the exact same problem, I noticed 0.6.5 seems to actually launch but some of the mods require  >=0.7.1 (and idk how they got it to work)

**Comment by HerpDerpinstine** [comment]
Please retry using MelonLoader v0.7.2-ci.2348 nightly.
I have just pushed some changes to possibly address this issue.

**Comment by Snoergee** [comment]
My friend has the same issue on Windows 11, exact same log too and we tried the newest nightly builds, different installation folders and other things but it didn't work. Versions under like 0.6.6 worked but the mods need newer versions. It works fine for me but and I'm on Linux.

**Comment by LatimerHL** [comment]
@HerpDerpinstine This issue still exists on Windows 11 (Home Edition) 23H2. I also tried v0.7.2 and latest v0.7.3 nightly build but failed.

> [02:34:50.210] ------------------------------
> [02:34:50.215] MelonLoader v0.7.1 Open-Beta
> [02:34:50.218] OS: Windows 11
> [02:34:50.218] Hash Code: E02D6B4281E511A9F1EA88CD1737B993A6B9C7C5566EFBE68300B1FCF1479C14
> [02:34:50.219] ------------------------------
> [02:34:50.222] Game Type: Il2cpp
> [02:34:50.227] Game Arch: x64
> [02:34:50.229] ------------------------------
> [02:34:50.230] Command-Line: 
> [02:34:50.230] ------------------------------
> [02:34:50.232] Core::BasePath = E:\steam\steamapps\common\Slime Rancher 2
> [02:34:50.232] Game::BasePath = E:\steam\steamapps\common\Slime Rancher 2
> [02:34:50.233] Game::DataPath = E:\steam\steamapps\common\Slime Rancher 2\SlimeRancher2_Data
> [02:34:50.233] Game::ApplicationPath = E:\steam\steamapps\common\Slime Rancher 2\SlimeRancher2.exe
> [02:34:50.234] Runtime Type: net6
> [02:34:50.474] ------------------------------
> [02:34:50.475] Game Name: SlimeRancher2
> [02:34:50.475] Game Developer: MonomiPark
> [02:34:50.478] Unity Version: 2021.3.28f1
> [02:34:50.479] Game Version: 1.1.1 [20260113175555-106213]
> [02:34:50.480] ------------------------------
> 
> [02:34:51.413] Preferences Loaded!
> 
> [02:34:51.436] Loading UserLibs...
> [02:34:51.441] 0 UserLibs loaded.
> 
> [02:34:51.442] Loading Plugins...
> [02:34:51.450] 0 Plugins loaded.
