### ISSUE TITLE
[Bug]: Bootstrap sometimes not finding dotnet6

### ISSUE THREAD

**Issue by sorano** [LavaGang/MelonLoader#1023]
### All of the following criteria must be met

- [x] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [x] Changed the title so that it doesn't just says "[Bug]: "
- [x] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [x] Tried reinstalling the Game.
- [x] Tried reinstalling MelonLoader.
- [x] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

When trying to use Melonloader on Linux with Il2Cpp games it doesn't start and this is seen in latest.log

`[10:01:42.483] [MelonLoader.Bootstrap] Failed to load Hostfxr
`

According to Kibbles The Rexouiumon discord there's been a regression that caused this bug to resurface since it used to work. Version 6.0 and up (incl. nightly) does not work currently.

### Did you attach your log file?

Select an option below

**Comment by baebypowder** [comment]
I have also been experiencing this issue using SteamOS. Net 6.0 is installed and working(checked via konsole) but melonloader does not start up with the game. I have also made sure to use the correct launch command in steam properties for the game I am modding(megabonk).

**Comment by qdtpptpg2h-gif** [comment]
Reporting the same issue on SteamOS as well. After running the installer, the directories are created in the expected Steam path. This includes two dependencies subdirectories within melonloader.

But when executing the relevant game (Megabonk), it appears the console does not load and no config files are written despite there being mod dlls in the appropriate folder.

**Comment by HerpDerpinstine** [comment]
Please retry using ML 0.7.2-ci.2363.
I have just pushed changes to the DotNet initialization that might address this issue.

**Comment by longirun** [comment]
Confirm the same issue on arch Manjaro Linux. I running game via Steam.
My ```Latest.log``` contains only this on both ```0.7.2-ci.2367``` and ```0.7.2-ci.2363``` nightly builds:
```
[13:16:54.824] [BS DEBUG] Opening stream to cached log
```

On the latest stable ```0.7.1```:
```
[13:21:52.535] [BS DEBUG] Opening stream to cached log
[13:21:52.535] [BS DEBUG] Plt hooked dlsym successfully
[13:21:53.176] [BS DEBUG] Redirecting il2cpp_init
[13:21:53.176] [BS DEBUG] Redirecting il2cpp_runtime_invoke
[13:21:53.181] [BS DEBUG] In init detour
[13:21:53.219] [BS DEBUG] Attempting to load hostfxr
[13:21:53.220] [MelonLoader.Bootstrap] Failed to load Hostfxr
[13:21:53.420] [BS DEBUG] Invoke hijacked
```

Is there any way to add more logging? I've made ```debug_mode = true``` already.

```
>> dotnet --info
Пакет SDK для .NET (отражающий любой global.json):
 Version:   6.0.136
 Commit:    d638663530

Среда выполнения:
 OS Name:     manjaro
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.136/

Host:
  Version:      9.0.9
  Architecture: x64
  Commit:       999243871a

.NET SDKs installed:
  6.0.136 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.NETCore.App 6.0.36 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by KillerX629** [comment]
Can confirm this is still an Issue on the latest nightly build 0.7.2-ci.2385
additionally, logs don't appear on this version.

dotnet --info

Host:
Version:      10.0.0
Architecture: x64
Commit:       b0f34d51fc
RID:          arch-x64

.NET SDKs installed:
No SDKs were found.

.NET runtimes installed:
Microsoft.NETCore.App 7.0.20 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 10.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
None

Environment variables:
Not set

global.json file:
Not found

Learn more:
https://aka.ms/dotnet/info

Download .NET:
https://aka.ms/dotnet/download

**Comment by alardev** [comment]
@HerpDerpinstine It appears to me that this issue has something to do with getting the path to the libhostfxr.so 

https://github.com/LavaGang/MelonLoader/blob/e1ad3a0647f0d0bc10d261619560c3c57f896974/MelonLoader.Bootstrap/RuntimeHandlers/Il2Cpp/Dotnet.cs#L45

It appears the shim library fails to guess the possible locations of the dotnet installation. AFAICS it needs DOTNET_ROOT a env variable with a valid path to the dotnet root directory.
```cs
    [DllImport("*", CharSet = hostfxrCharSet)]
    private static extern int get_hostfxr_path(StringBuilder buffer, ref nint bufferSize, nint parameters);
```

current workaround is to set the hostfxr path manually in the Loader.cfg OR provide DOTNET_ROOT environment variable that points to the dotnet root directory.

Note: I placed my dotnet inside the MelonLoader folder since i'm running inside Flatpak Steam environment. This is quite a common issue with loading external libraries which do not have access to host ENV variables.

```ini
# Manually defines the HostFXR path to use for DotNet Initialization. Equivalent to the '--melonloader.hostfxr' launch option
hostfxr_path_override = "/var/home/alar/.steam/steam/steamapps/common/TheLongDark/MelonLoader/dotnet/host/fxr/6.0.36/libhostfxr.so"
```
alternatively a launch argument may be supplemented with the DOTNET_ROOT env var.

```bash
DOTNET_ROOT="/var/home/alar/.steam/steam/steamapps/common/TheLongDark/MelonLoader/dotnet/" LD_LIBRARY_PATH="/var/home/alar/.local/share/Steam/steamapps/common/TheLongDark:$LD_LIBRARY_PATH" LD_PRELOAD="MelonLoader.Bootstrap.so" %command%
```
After that the Loader manages to progress forwards

Additionally there appears to be some work already made on this pull request #1062 

However non-windows OS-s are not handled unfortunately.

I think it's best to include this information in the Linux Native installation instructions on wiki, especially for Il2Cpp section since it won't work at all without dotnet.
