### ISSUE TITLE
[Bug]: INTERNAL FAILURE (Failed to create Logs folder)

### ISSUE THREAD

**Issue by mme200013** [LavaGang/MelonLoader#227]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Melonloader verison 0.4.1 

Game: Tale of Immortal

Whenever I try to start the game a cmd like screen pops up with the following (INTERNAL FAILURE) (Failed to create Logs Folder).
I tried the latest version, and it doesn't even show any pop ups or anything.
I know that this game is not officially supported, however, many other players are playing it using this loader.

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by mme200013** [comment]
I fixed it.
Apparently the gamedir had Chinese characters in its folder name, that messed up something, when I removed the Chinese characters from the folder's name, it worked just fine.

**Comment by shaneteague** [comment]
mine have not got the chinese name and it still dont work. Please help
