### ISSUE TITLE
Bloons tower defense 6 crashing without showing start screen but while showing the command prompt looking thing.

### ISSUE THREAD

**Issue by FusionTheGamer** [LavaGang/MelonLoader#513]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/12389241/Latest.log)
Or alternatively if you don't want to download the log:
[16:20:31.227] ------------------------------
[16:20:31.381] MelonLoader v0.6.1 Open-Beta
[16:20:31.383] OS: Windows 10
[16:20:31.383] Hash Code: 696B58144EEC73C72FA36A811CA73312EEE4EC28AD5E3527BDA1E14F388A
[16:20:31.383] ------------------------------
[16:20:31.384] Game Type: Il2cpp
[16:20:31.384] Game Arch: x64
[16:20:31.384] ------------------------------
[16:20:31.385] Core::BasePath = D:\Steam\steamapps\common\BloonsTD6
[16:20:31.385] Game::BasePath = D:\Steam\steamapps\common\BloonsTD6
[16:20:31.385] Game::DataPath = D:\Steam\steamapps\common\BloonsTD6\BloonsTD6_Data
[16:20:31.385] Game::ApplicationPath = D:\Steam\steamapps\common\BloonsTD6\BloonsTD6.exe
[16:20:31.385] Runtime Type: net6
[16:20:31.639] ------------------------------
[16:20:31.639] Game Name: BloonsTD6
[16:20:31.639] Game Developer: Ninja Kiwi
[16:20:31.641] Unity Version: 2021.3.16f1
[16:20:31.641] Game Version: 38.3
[16:20:31.642] ------------------------------

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
should be fixed in nightly.

**Comment by FusionTheGamer** [comment]
what does nightly mean?

**Comment by PikaPiksmth** [comment]
i have this too i just deleted the BTD6EpicGamesModCompat and then installed a older version of that the 1.1 and it still crashes but now i think its the melon loader ill reinstall it

**Comment by rakosi2** [comment]
[This is nightly](https://nightly.link/LavaGang/MelonLoader/workflows/build/alpha-development) use version MelonLoader.Windows.x64.CI.Release

**Comment by rakosi2** [comment]
Seems like this issue is resolved, If it wasn't, feel free to reopen it.
