### ISSUE TITLE
[Bug]: Downloading UnityDependencies error 

### ISSUE THREAD

**Issue by XHXJ** [LavaGang/MelonLoader#538]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

Downloading https://github.com/LavaGang/Unity-Runtime-Libraries/raw/master/2023.1.15.zip

2023.1.15.zip This file does not exist, download error . mode is not loaded properly

```
[22:18:43.126] [Il2CppAssemblyGenerator] Downloading https://github.com/LavaGang/Unity-Runtime-Libraries/raw/master/2023.1.15.zip to D:\BaiduNetdiskDownload\RJ01072476\RJ01072476\MelonLoader\Dependencies\Il2CppAssemblyGenerator\UnityDependencies_2023.1.15.zip
[22:18:43.744] [Il2CppAssemblyGenerator] System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at MelonLoader.Il2CppAssemblyGenerator.Extensions.DownloadFile(HttpClient client, String url, String dest) in D:\a\MelonLoader\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Extensions.cs:line 10
   at MelonLoader.Il2CppAssemblyGenerator.FileHandler.Download(String url, String destination) in D:\a\MelonLoader\MelonLoader\Dependencies\Il2CppAssemblyGenerator\FileHandler.cs:line 34
[NewEntryPoint] Starting.
```

[Latest.log](https://github.com/LavaGang/MelonLoader/files/12819447/Latest.log)

### Did you attach your log file?

- [x] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
@DragonPlayerX

**Comment by DragonPlayerX** [comment]
Should work now

**Comment by PranitModak** [comment]
@DragonPlayerX  still getting an error for unity dependencies
https://github.com/LavaGang/Unity-Runtime-Libraries/raw/master/2020.3.14.zip 
![image](https://github.com/LavaGang/MelonLoader/assets/43670565/d8544afd-8e1b-4a33-954c-f2abeba94f26)
